jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

   defaults:
      run:
        shell: bash
        #Inform a working directory if .tf files are not in root folder
        working-directory: ./terraform 
